server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      forward-headers-strategy: framework
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            #- StripPrefix=1
            - PreserveHostHeader
        - id: statis-service
          uri: lb://statis-service
          predicates:
            - Path=/statis/**
          filters:
            - PreserveHostHeader
        - id: history-service
          uri: lb://history-service
          predicates:
            - Path=/history/**
          filters:
            - PreserveHostHeader


      default-filters:
        - RemoveRequestHeader=Cookie

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:5173
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

    discovery:
      locator:
        enabled: true
        lower-case-service-id: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway.filter: DEBUG
    org.springframework.security: DEBUG
    com.budgetmate.user.security: DEBUG
    org.springframework.web: DEBUG
